name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'

      - name: dotnet build
        run: dotnet build

      - name: npm install
        run: npm install
        working-directory: DotnetTemplate.Web

      - name: dotnet test
        run: dotnet test

      - name: npm test
        run: npm t
        working-directory: DotnetTemplate.Web

      - name: npm lint
        run: npm run lint
        working-directory: DotnetTemplate.Web